name: "Solar System"
env:
  MONGO_URI: "mongodb://localhost:27017/solar-system"
  MONGO_USER: ${{vars.MONGO_USER}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
on:
  push:
    branches:
      - main
      - "feature/*"

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v7
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm run test
